Better testimonials
ezhukov/gg-web pull request #5
Opened 2024-01-23 09:02 UTC by ezhukov

TBD

2024-01-23 12:37 UTC, btbroot requested changes
Largely fine, with few remarks to be addressed

2024-01-23 12:37 UTC, btbroot commented on data/en/testimonial.yml
>        content : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium minima ex, quia error, deserunt voluptatibus repellendus? Incidunt eligendi aliquam repellat molestias, vel sed o
This placeholder doesn't make sense to be taken (and published). Shouldn't we wait up for the actual testimonial instead?

2024-01-23 12:37 UTC, btbroot commented on data/en/testimonial.yml
> +      content : Al was doing a great job leading the Dev-Ops efforts at Basemark. He is very strong technically and we could always rely on him to get things done. I particularly appreciated his know
```suggestion
      content : Al was doing a great job leading the DevOps efforts at Basemark. He is very strong technology-wise, and we could always rely on him to get things done. I particularly appreciated his knowledge of modern Behavior Driven Development approaches.
```

2024-01-23 12:37 UTC, btbroot commented on themes/meghna-hugo/layouts/partials/testimonial.html
Add their LinkedIn profile links as well, maybe?

2024-01-23 13:13 UTC, ezhukov commented on data/en/testimonial.yml
>        content : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium minima ex, quia error, deserunt voluptatibus repellendus? Incidunt eligendi aliquam repellat molestias, vel sed o
Yes, absolutely, that's why it's still in draft.

2024-01-26 12:02 UTC, btbroot approved these changes
Fine

2024-01-26 12:03 UTC, merged